version: '3'
services:
  db:
    container_name: bot_db
    image: postgres:14
    env_file:
      - ./.env
    expose:
      - '${POSTGRES_PORT}'
    ports:
      - '5433:${POSTGRES_PORT}'
    volumes:
      - pgdata:/var/lib/postgresql/data
  pgadmin:
    container_name: bot_pgadmin
    image: dpage/pgadmin4
    env_file:
      - ./.env
    ports:
      - '54322:80'
    depends_on:
      - db
    logging:
      driver: none
  bot:
    container_name: bot
    build:
      context: .
      dockerfile: Dockerfile.dev
    expose:
      - '${BOT_PORT}'
    ports:
      - '${BOT_PORT}:${BOT_PORT}'
    depends_on:
      - db
    volumes:
      - ./:/wise-old-man/discord-bot
      - /wise-old-man/discord-bot/node_modules/
    command: './wait-for-it.sh -t 30 ${DB_HOST}:${POSTGRES_PORT} -- npm run watch'
volumes:
  pgdata:
